######################################################################
# Automatically generated by qmake (3.0) ?? 2? 18 14:13:16 2017
######################################################################

TEMPLATE = app
TARGET = model_view1
INCLUDEPATH += .

# Input
HEADERS += mymodel.h
SOURCES += main.cpp mymodel.cpp
#target.path = ~/QT/afdf
QT += widgets
