######################################################################
# Automatically generated by qmake (3.0) ?? 2? 28 14:18:44 2017
######################################################################

TEMPLATE = app
TARGET = model_view1
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mymodel.h
SOURCES += main.cpp mainwindow.cpp mymodel.cpp
QT += widgets
