######################################################################
# Automatically generated by qmake (3.0) ?? 3? 5 20:58:59 2017
######################################################################

TEMPLATE = app
TARGET = model_view1
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mydelegate.h mymodel.h
SOURCES += main.cpp mainwindow.cpp mydelegate.cpp mymodel.cpp
QT += widgets
